[project]
name = "functions"
version = "0.1.0"
description = "Lambda function (container-mode)handlers"
dependencies = ["pydantic-ai", "pydantic", "openai"]
requires-python = "==3.11.*"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
