# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class InvokeModelFunction:
        name: str
        type: str
    class WebSocketApi:
        managementEndpoint: str
        type: str
        url: str

